version: '3.8'

services:
  # --- NUR DAS PHP FRONTEND & LOGIK ---
  web_frontend:
    build: ./app
    container_name: akeneo_web_app
    restart: always
    ports:
      - "${APP_PORT:-8085}:80"  # Nutzt weiterhin deinen Port 8098 aus Portainer
    environment:
      - API_BASE_URL
      - TOKEN_URL
      - API_USERNAME
      - API_PASSWORD
      - CLIENT_ID
      - CLIENT_SECRET